site_name: "Research Software Guidelines"
docs_dir: docs
nav:
  - index.md
  - "What is research software?":
      - rs/definitions-examples.md
      - rs/is-developing-rs.md
  - "Software Management Plans":
      - smp/smp-intro.md
      - smp/sciwiz.md
  - "Research Software best practices":
      - best-practices/overview.md
      - best-practices/identity.md
      - best-practices/motivation-scope.md
      - best-practices/risks.md
      - best-practices/planning.md
      - best-practices/sharing-licensing.md
      - best-practices/metadata.md
      - best-practices/documentation-community.md
      - best-practices/interoperability.md
      - best-practices/testing-quality.md
      - best-practices/versioning-releases.md
  - "Resources":
      - resources/organizations.md
      - resources/abbreviations.md
      - resources/contacts.md
  - about.md
repo_url: https://github.com/LUMC-DCC/rs-guidelines
repo_name: rs-guidelines
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: PT Sans
  palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
markdown_extensions:
  - abbr
hooks:
  - hooks/content.py
  - hooks/permalinks.py
plugins:
  - search
site_url: https://lumc-dcc.github.io/rs-guidelines
edit_uri: ""
copyright: 'Research Software Guidelines by LUMC DCC, licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
extra_css:
  - stylesheets/extra.css