[project]
name = "rs-guidelines"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "CC-BY-4.0"
license-files = ["LICENSE"]
dependencies = [
    "PyYAML==6.0.*",
    "zensical==0.0.*"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
